name: docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      DOCS_GA_ID: G-CTB8FQ7VMW
      NODE_VERSION: '16'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn

      - name: Build documentation site
        run: yarn docs:build
        
      - name: Create CNAME
        run: cd .vuepress/dist && echo "www.vmo.design" > CNAME

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          target_branch: gh-pages
          build_dir: .vuepress/dist
        env:
          GH_PAT: ${{ secrets.ACTION_TOKEN }}
